### ISSUE TITLE
MouseInstruct failing to execute given input

### ISSUE THREAD

**Issue by Megant88** [khanxbahria/MouseInstruct#2]
Hey :0,
Im a great fan of your project and integrated it also into my projects, check my profile for that,
people ask me for help when they wanna use my project, yet I have a special case, a good friend of mine who had the same idea has troubles installing MouseInstruct onto his arduino, after some hard debugging I figured that the arduino simply doesnt accept execute mousemove using HID. Im not exactly sure why, I installed this on many friends already always worked great. We actually tried 2 r3's on both it didnt execute mousemove, also reseted pc. None of it worked. It finds the device, yet cant move it. I believe the problem is related to the ImprovedMouse file, it fails to send rawreport or it does but the arduino doesnt respond. In anycase for info,
he uses LOGITECH Super Light 2.
I'd be very grateful if you can reach out tg: @tokifynet, discord: @depressed.developer, I can pay you for your time. Thanks!

**Comment by LXYlegend** [comment]
Have you solved it, bro?

**Comment by Megant88** [comment]
Hello, no this issue still persists.

**Comment by Megant88** [comment]
Hello, this issue is resolved, the problem was not MouseInstruct, nor his mouse. But more his keyboard, his keyboard had a function with the pingcode 0x9, that way it messed with the hid controller, the solution is to increase the value of the pingcode or// use different keyboard
